### ISSUE TITLE
Only support limited properties?

### ISSUE THREAD

**Issue by zhouhao27** [evgenyneu/SpringAnimationCALayer#1]
Is it working for properties like bounds, frame or scale? Thanks

**Comment by evgenyneu** [comment]
Hi, you can animate scale by supplying `transform.scale` argument. Bounds is animatable, as well as position: `position.y`. Frame is not animatable. 

Here is the list of animatable properties: https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CoreAnimation_guide/AnimatableProperties/AnimatableProperties.html

**Comment by evgenyneu** [comment]
Closing this for now. Feel free to re-open if you need.
